[SDKS-6274] Create Interface SplitSyncTask
splitio/java-client pull request #357
Opened 2022-11-28 21:36 UTC by nmayorsplit

2022-11-28 21:41 UTC, mmelograno requested changes

2022-11-28 21:41 UTC, mmelograno commented on client/src/main/java/io/split/engine/experiments/SplitSyncTask.java
> +    void startPeriodicFetching();
let's call it start

2022-11-29 15:29 UTC, nmayorsplit commented on client/src/main/java/io/split/engine/experiments/SplitSyncTask.java
> +    void startPeriodicFetching();
I changed it.

2022-11-30 17:47 UTC, sanzmauro approved these changes

2022-11-30 22:05 UTC, mmelograno approved these changes

2022-12-01 00:25 UTC, merged