Disco week
splitio/java-client pull request #408
Opened 2023-05-12 19:01 UTC by nmayorsplit

Update change logs and version for testing apps

2023-05-12 19:37 UTC, sanzmauro approved these changes

2023-05-16 13:54 UTC, mmelograno requested changes

2023-05-16 13:54 UTC, mmelograno commented on client/src/main/java/io/split/engine/evaluator/Labels.java
> +    public static final String NOT_IN_FEATURE_FLAG = "not in feature flag";
this is a breaking change

2023-05-16 15:55 UTC, mmelograno approved these changes

2023-05-16 16:04 UTC, nmayorsplit commented on client/src/main/java/io/split/client/HttpSegmentChangeFetcher.java
> +                    _log.error("factory instantiation: you passed a client side type sdk_key, " +
updated

2023-05-16 16:05 UTC, nmayorsplit commented on client/src/main/java/io/split/client/SplitClientImpl.java
> +                _log.error(String.format("%s: feature flag names must be a non-empty array", methodEnum.getMethod()));
updated

2023-05-16 17:11 UTC, merged