[SDKS-7514] Add flagSetFilter config
splitio/java-client pull request #432
Opened 2023-09-06 20:16 UTC by nmayorsplit

2023-09-07 14:36 UTC, mmelograno requested changes

2023-09-07 14:36 UTC, mmelograno commented on client/src/main/java/io/split/client/SplitClientConfig.java
> +        private List<String> _flagSetsFilter = null;
empty will be better instead of null

2023-09-07 17:46 UTC, nmayorsplit commented on client/src/main/java/io/split/client/SplitClientConfig.java
> +        private List<String> _flagSetsFilter = null;
Updated.

2023-09-08 13:51 UTC, sanzmauro approved these changes

2023-09-08 18:28 UTC, mmelograno approved these changes

2023-09-08 19:10 UTC, merged