added less than or equal semver matcher
splitio/java-client pull request #500
Opened 2024-04-26 18:53 UTC by chillaq

2024-05-02 15:01 UTC, sanzmauro requested changes

2024-05-02 15:01 UTC, sanzmauro commented on client/src/main/java/io/split/engine/matchers/LessThanOrEqualToSemverMatcher.java
> +        if (matchValue == null) {
you can check here if `_semVer != null`

2024-05-02 23:01 UTC, chillaq commented on client/src/main/java/io/split/engine/matchers/LessThanOrEqualToSemverMatcher.java
> +        if (matchValue == null) {
will update

2024-05-03 19:15 UTC, sanzmauro approved these changes

2024-05-03 19:24 UTC, merged